"""relationships and json lead to company

Revision ID: 7fd112b3a10b
Revises: a46da0e4dfdd
Create Date: 2017-05-30 16:31:37.568204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fd112b3a10b'
down_revision = 'a46da0e4dfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead')
    op.add_column('company', sa.Column('lead_data', sa.JSON(), nullable=True))
    op.add_column('vacancy', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancy', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    pass

